### ISSUE TITLE
Implement Vehicle-controller (First Draft)

### ISSUE THREAD

**Issue by AxelBo** [ll7/paf21-1#20]
**Tasks:**
- implement velocity control
- implement steering control
- integrate the component with other ROS nodes

**Difficulties:**
- figure out whether the suggested input data (route waypoints + target speed + GPS) is sufficient:
  - what about the steering angle? how to retain this information?
    - *yes, it's sufficient. given the vehicle's position + orientation and the route's next aim point, the steering angle can be determined using math.atan2*
- figure out how to translate the input data into control signals:
  - use a PID controller, but how? are there libs for this?
    - *e.g. there's the simple-pid pip package for Python which is used by the Ackermann Control*
  - does Ackermann Control already handle the PID controller part? (-> just forward the steering angle + target speed and that's it?)
    - *seems to be the case, but we can also manually override the temporal difference for both steering angle and driving speed*
- for steering, is the *Stanley Method* the right approach? Do we have sufficient information to compute it?
  - *apparently yes, but it will be part of the next sprint #30*

**Goal:**
- [x] make the car drive a given route reliably (use the scenario runner to make the progress measurable)
- [x] add component-level tests to mock the input of other components
- [x] make the vehicle controller interact with local planner / sensors via Docker + ROS

see MVP implementation for demo: https://github.com/ll7/paf21-1/releases/tag/vehicle-controller-mvp
